name: 'UI tests'
on:   
  push:
      branches: [ main ]
jobs:
  react-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        working-directory: ./frontend
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run build then tests
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
          npm test